# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    filter_sets:
        pub:
            quality: 75
            filters:
                thumbnail:
                    size: [70,70]
                    mode: outbound
        thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [360,230]
                    mode: outbound
        hero:
            quality: 75
            filters:
                thumbnail:
                    size: [150,150]
                    mode: outbound
        article:
            quality: 75
            filters:
                thumbnail:
                    size: [291,293]
                    mode: outbound
        category:
            quality: 75
            filters:
                thumbnail:
                    size: [291,293]
                    mode: outbound

        new:
            quality: 75
            filters:
                thumbnail:
                    size: [700,310]
                    mode: outbound
        resource:
            quality: 75
            filters:
                thumbnail:
                    size: [350,197]
                    mode: outbound
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
