vich_uploader:
    db_driver: orm

    mappings:
    
        article_image:
            uri_prefix: /assets/img/articles
            upload_destination: '%kernel.project_dir%/public/assets/img/articles'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        gallery_image:
            uri_prefix: /assets/img/galleries
            upload_destination: '%kernel.project_dir%/public/assets/img/galleries'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        new_image:
            uri_prefix: /assets/img/news
            upload_destination: '%kernel.project_dir%/public/assets/img/news'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        slider_image:
            uri_prefix: /assets/img/sliders
            upload_destination: '%kernel.project_dir%/public/assets/img/sliders'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        user_image:
            uri_prefix: /assets/img/users
            upload_destination: '%kernel.project_dir%/public/assets/img/users'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
