<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'dev', // Default : prod
  'APP_SECRET' => 'b522766161109c5c0b9a173e003688b8',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/ohsdb',
);
