controllers:
    resource: ../../src/Controller/
    type: annotation

admin:
    resource: ../../src/Controller/Admin/
    type: annotation
    prefix: /fr/admin

api:
    resource: ../../src/Controller/Api/
    type: annotation
    prefix: /api/

kernel:
    resource: ../../src/Kernel.php
    type: annotation
