index:
  path:
    fr: /
    en: /en
  controller: App\Controller\DefaultController::index

annonce_show:
  path:
    fr: /{id}/annonce
    en: /{id}/annonce
  controller: App\Controller\DefaultController::annonce_show

new_show:
  path:
    fr: /{id}/new
    en: /{id}/new
  controller: App\Controller\DefaultController::new_show

region_show:
  path:
    fr: /{id}/region
    en: /{id}/region
  controller: App\Controller\DefaultController::region_show

level_show:
  path:
    fr: /{id}/class
    en: /{id}/class
  controller: App\Controller\DefaultController::level_show


teachers_index:
  path:
    fr: /teachers
    en: /teachers
  controller: App\Controller\DefaultController::teachers_index

about_index:
  path:
    fr: /about
    en: /about
  controller: App\Controller\DefaultController::about_index